version: '3'

volumes:
  node-modules:
    external: true
  mongo-data:
    external: true

services:
  dev:
    #    links:
    #      - "mongo"
    #      - "mongo-express"
    image: node:lts-alpine
    working_dir: /usr/src/service
    volumes:
      - node-modules:/usr/src/service/node_modules
      - .:/usr/src/service
    ports:
    - 8080:8080
    environment:
      - NODE_ENV=development
    command: npm run dev
